export interface VerifiedCOA {
  id: string | number
  product: string
  category: string
  purity: string
  batch: string
  analyzed: string
  lab: string
  formula?: string
  molecularWeight?: string
  observedWeight?: string
  method?: string
  status?: string
  coaUrl?: string | null
  productSlug?: string
  notes?: string
}

export const FALLBACK_COAS: VerifiedCOA[] = [
  {
    id: 101,
    product: 'BPC-157 5mg',
    category: 'Tissue & Healing',
    purity: '99.4%',
    batch: 'VR-BPC-2603A',
    analyzed: 'Aug 28, 2026',
    lab: 'Colmar Analytical Laboratories (USA)',
    formula: 'C62H98N16O22',
    molecularWeight: '1419.53 g/mol',
    observedWeight: '1419.51 g/mol',
    method: 'RP-HPLC (C18 column) & ESI-MS',
    status: 'PASS • Confirmed ≥99%',
    coaUrl: null,
    productSlug: 'bpc-157-5mg',
    notes: 'Single prominent chromatographic peak at retention time 14.82 min. Area normalization confirms 99.42% purity.',
  },
  {
    id: 102,
    product: 'BPC-157 10mg',
    category: 'Tissue & Healing',
    purity: '99.6%',
    batch: 'VR-BPC-2603B',
    analyzed: 'Aug 26, 2026',
    lab: 'Jan Scientific Labs Inc. (USA)',
    formula: 'C62H98N16O22',
    molecularWeight: '1419.53 g/mol',
    observedWeight: '1419.50 g/mol',
    method: 'RP-HPLC & MALDI-TOF MS',
    status: 'PASS • Confirmed ≥99%',
    coaUrl: null,
    productSlug: 'bpc-157-10mg',
    notes: 'Sequence identity verified via tandem mass spec fragmentation. Heavy metal residuals below 0.05 ppm threshold.',
  },
  {
    id: 103,
    product: 'TB-500 (Thymosin Beta-4) 5mg',
    category: 'Tissue & Healing',
    purity: '99.2%',
    batch: 'VR-TB-2601A',
    analyzed: 'Aug 21, 2026',
    lab: 'Colmar Analytical Laboratories (USA)',
    formula: 'C212H350N56O78S',
    molecularWeight: '4963.49 g/mol',
    observedWeight: '4963.52 g/mol',
    method: 'Ion-Exchange HPLC & Electrospray MS',
    status: 'PASS • Confirmed ≥99%',
    coaUrl: null,
    productSlug: 'tb-500-5mg',
    notes: 'High conformational stability verified. Mass deviation within ±0.03 Da tolerance.',
  },
  {
    id: 104,
    product: 'GHK-Cu 50mg',
    category: 'Cosmetic & Dermatological',
    purity: '99.7%',
    batch: 'VR-GHK-2602A',
    analyzed: 'Aug 18, 2026',
    lab: 'Alliance Bio-Analytical Services',
    formula: 'C14H24CuN6O4',
    molecularWeight: '403.93 g/mol',
    observedWeight: '403.91 g/mol',
    method: 'UV-Vis Spectrophotometry & HPLC',
    status: 'PASS • Confirmed ≥99%',
    coaUrl: null,
    productSlug: 'ghk-cu-50mg',
    notes: 'Stoichiometric copper (Cu2+) chelation verified by absorbance peak at 605 nm. Residual acetic acid < 1.2%.',
  },
  {
    id: 105,
    product: 'NAD+ 500mg',
    category: 'Longevity & Cellular',
    purity: '99.8%',
    batch: 'VR-NAD-2604A',
    analyzed: 'Aug 15, 2026',
    lab: 'Jan Scientific Labs Inc. (USA)',
    formula: 'C21H27N7O14P2',
    molecularWeight: '663.43 g/mol',
    observedWeight: '663.44 g/mol',
    method: 'RP-HPLC with Photodiode Array (PDA)',
    status: 'PASS • Confirmed ≥99%',
    coaUrl: null,
    productSlug: 'nad-plus-500mg',
    notes: 'Oxidized β-nicotinamide adenine dinucleotide purity 99.82%. Moisture content below 2.0% w/w by Karl Fischer.',
  },
  {
    id: 106,
    product: 'Semaglutide 5mg',
    category: 'Metabolic Research',
    purity: '99.5%',
    batch: 'VR-SEM-2602A',
    analyzed: 'Aug 11, 2026',
    lab: 'Colmar Analytical Laboratories (USA)',
    formula: 'C187H291N45O59',
    molecularWeight: '4113.58 g/mol',
    observedWeight: '4113.61 g/mol',
    method: 'RP-HPLC & High-Resolution Orbitrap MS',
    status: 'PASS • Confirmed ≥99%',
    coaUrl: null,
    productSlug: 'semaglutide-5mg',
    notes: 'Synthetic GLP-1 receptor agonist peptide. Diacid spacer and Aib substitution verified by MS/MS.',
  },
  {
    id: 107,
    product: 'Tirzepatide 10mg',
    category: 'Metabolic Research',
    purity: '99.6%',
    batch: 'VR-TRZ-2601B',
    analyzed: 'Aug 07, 2026',
    lab: 'Vanguard Chemical Testing Group',
    formula: 'C225H348N48O68',
    molecularWeight: '4813.45 g/mol',
    observedWeight: '4813.40 g/mol',
    method: 'Dual-Column HPLC & Mass Spec',
    status: 'PASS • Confirmed ≥99%',
    coaUrl: null,
    productSlug: 'tirzepatide-10mg',
    notes: 'Dual GIP/GLP-1 agonist analog. Purity 99.64% by peak area normalization at 214 nm.',
  },
  {
    id: 108,
    product: 'Epithalon 50mg',
    category: 'Longevity & Cellular',
    purity: '99.3%',
    batch: 'VR-EPI-2603A',
    analyzed: 'Aug 02, 2026',
    lab: 'Jan Scientific Labs Inc. (USA)',
    formula: 'C14H22N4O9',
    molecularWeight: '390.35 g/mol',
    observedWeight: '390.33 g/mol',
    method: 'RP-HPLC & Quadrupole Mass Spec',
    status: 'PASS • Confirmed ≥99%',
    coaUrl: null,
    productSlug: 'epithalon-50mg',
    notes: 'Tetrapeptide (Ala-Glu-Asp-Gly) sequence confirmed. Lyophilized cake stability rated for 24 months at -20°C.',
  },
  {
    id: 109,
    product: 'CJC-1295 (No DAC) 5mg',
    category: 'Metabolic Research',
    purity: '99.4%',
    batch: 'VR-CJC-2601A',
    analyzed: 'Jul 28, 2026',
    lab: 'Colmar Analytical Laboratories (USA)',
    formula: 'C152H252N44O42',
    molecularWeight: '3367.97 g/mol',
    observedWeight: '3367.92 g/mol',
    method: 'RP-HPLC (Gradient acetonitrile/water/TFA)',
    status: 'PASS • Confirmed ≥99%',
    coaUrl: null,
    productSlug: 'cjc-1295-no-dac-5mg',
    notes: 'Modified GRF (1-29) analog with D-Ala2, Gln8, Ala15, Leu27 substitutions confirmed.',
  },
  {
    id: 110,
    product: 'Ipamorelin 5mg',
    category: 'Metabolic Research',
    purity: '99.5%',
    batch: 'VR-IPA-2602A',
    analyzed: 'Jul 24, 2026',
    lab: 'Alliance Bio-Analytical Services',
    formula: 'C38H49N9O5',
    molecularWeight: '711.85 g/mol',
    observedWeight: '711.88 g/mol',
    method: 'RP-HPLC & High-Resolution ESI-MS',
    status: 'PASS • Confirmed ≥99%',
    coaUrl: null,
    productSlug: 'ipamorelin-5mg',
    notes: 'Pentapeptide growth hormone secretagogue analog. Zero detectable truncated fragment impurities.',
  },
  {
    id: 111,
    product: 'AOD-9604 5mg',
    category: 'Metabolic Research',
    purity: '99.2%',
    batch: 'VR-AOD-2601C',
    analyzed: 'Jul 19, 2026',
    lab: 'Colmar Analytical Laboratories (USA)',
    formula: 'C78H123N23O23S2',
    molecularWeight: '1815.10 g/mol',
    observedWeight: '1815.06 g/mol',
    method: 'RP-HPLC & MALDI-TOF MS',
    status: 'PASS • Confirmed ≥99%',
    coaUrl: null,
    productSlug: 'aod-9604-5mg',
    notes: 'C-terminal fragment (177-191) with Tyr stabilization. Intact disulfide bridge verified.',
  },
  {
    id: 112,
    product: 'MOTS-c 10mg',
    category: 'Longevity & Cellular',
    purity: '99.6%',
    batch: 'VR-MOT-2602A',
    analyzed: 'Jul 15, 2026',
    lab: 'Jan Scientific Labs Inc. (USA)',
    formula: 'C101H152N28O22S2',
    molecularWeight: '2174.62 g/mol',
    observedWeight: '2174.58 g/mol',
    method: 'RP-HPLC & Orbitrap Tandem MS',
    status: 'PASS • Confirmed ≥99%',
    coaUrl: null,
    productSlug: 'mots-c-10mg',
    notes: 'Mitochondrial-derived 16-amino acid peptide. Single sharp chromatographic peak; area normalization 99.61%.',
  },
]
