import { BlogIndexPost } from '@/components/blog/BlogIndexClient'

export const DUMMY_BLOG_POSTS: BlogIndexPost[] = [
  {
    slug: 'tissue-repair-synergy-bpc-157-tb-500-ghk-cu',
    title: 'Tissue Repair Synergy: Exploring BPC-157, TB-500, and GHK-Cu in Advanced Protocols',
    category: 'Recovery protocols',
    excerpt: 'An in-depth analysis of angiogenesis acceleration, actin sequestering, and extracellular matrix remodeling through the combined administration of targeted research peptides.',
    imageSrc: '/veracue-images/veracue-research-grade-50mg-molecular-helix.png',
    readTime: '11 min read',
    date: 'August 14, 2026',
    sortDate: '2026-08-14T10:00:00Z',
  },
  {
    slug: 'glp-1-gip-receptor-agonism-metabolic-investigation',
    title: 'GLP-1 and Dual GIP Receptor Agonism: The Molecular Frontier of Metabolic Investigation',
    category: 'Metabolic research',
    excerpt: 'Evaluating the binding affinity profiles, sustained receptor kinetics, and insulinotropic signaling pathways of second and third-generation incretin mimetics in controlled laboratory models.',
    imageSrc: '/veracue-images/veracue-research-grade-50mg-dish-leaf-droplets.png',
    readTime: '14 min read',
    date: 'August 08, 2026',
    sortDate: '2026-08-08T14:30:00Z',
  },
  {
    slug: 'analytical-rp-hplc-interpreting-purity-mass-spec-reports',
    title: 'Analytical RP-HPLC: Interpreting Purity, Peak Resolution, & Mass Spectrometry Reports',
    category: 'Synthesis & Testing',
    excerpt: 'A laboratory guide to chromatographic peak resolution, area normalization percentage calculations, and identifying trifluoroacetate salt counterions on batch COA releases.',
    imageSrc: '/veracue-images/veracue-military-researcher-lab.jpg',
    readTime: '9 min read',
    date: 'July 29, 2026',
    sortDate: '2026-07-29T09:15:00Z',
  },
  {
    slug: 'reconstitution-chemistry-solvents-lyophilization-stability',
    title: 'Reconstitution Chemistry: Solvent Selection, Lyophilization Cakes, & Stability Kinetics',
    category: 'Recovery protocols',
    excerpt: 'Critical considerations when reconstituting sensitive peptide chains with bacteriostatic water versus sterile saline, including pH shifts and aggregation risks during long-term storage.',
    imageSrc: '/veracue-images/veracue-research-grade-50mg-ice-dropper.png',
    readTime: '8 min read',
    date: 'July 21, 2026',
    sortDate: '2026-07-21T11:00:00Z',
  },
  {
    slug: 'growth-hormone-secretagogue-dynamics-cjc-1295-ipamorelin',
    title: 'Growth Hormone Secretagogue Dynamics: Comparing CJC-1295 (DAC vs No DAC) & Ipamorelin',
    category: 'Growth research',
    excerpt: 'Differentiating between pulsatile pituitary signaling and sustained somatotrophic elevation across synthetic GHRH analogs and ghrelin receptor agonists in cellular assays.',
    imageSrc: '/veracue-images/veracue-peptides-multi-vials-collection-flatlay.webp',
    readTime: '13 min read',
    date: 'July 15, 2026',
    sortDate: '2026-07-15T16:20:00Z',
  },
  {
    slug: 'epithalon-cellular-longevity-telomerase-activation-models',
    title: 'Cellular Longevity & Telomerase Activation: Epithalon in In-Vitro Senescence Models',
    category: 'Growth research',
    excerpt: 'Examining synthetic tetrapeptide Epithalamin derivatives, heterochromatin remodeling, and cellular replicative capacity in mammalian longevity cell lines.',
    imageSrc: '/veracue-images/veracue-epithalon-50mg-water-ripples-landscape.webp',
    readTime: '10 min read',
    date: 'July 04, 2026',
    sortDate: '2026-07-04T12:00:00Z',
  },
  {
    slug: 'nad-plus-mitochondrial-respiration-oxidative-stress',
    title: 'NAD+ & Mitochondrial Respiration: Energy Substrate Transport in Oxidative Stress',
    category: 'Metabolic research',
    excerpt: 'How nicotinamide adenine dinucleotide governs sirtuin enzyme deacetylation and electron transport chain integrity during induced oxidative stress in cellular cultures.',
    imageSrc: '/veracue-images/veracue-nad-plus-500mg-cotton-cloud.webp',
    readTime: '12 min read',
    date: 'June 26, 2026',
    sortDate: '2026-06-26T08:45:00Z',
  },
  {
    slug: 'follistatin-myostatin-inhibition-skeletal-muscle-assays',
    title: 'Follistatin-344 vs Myostatin Inhibition: Molecular Pathways in Skeletal Muscle Assays',
    category: 'Muscle studies',
    excerpt: 'Mechanisms of TGF-beta superfamily antagonism, activin binding cascades, and hypertrophy biomarkers in in-vitro muscle culture investigations.',
    imageSrc: '/veracue-images/veracue-research-grade-50mg-gloved-hand.png',
    readTime: '15 min read',
    date: 'June 18, 2026',
    sortDate: '2026-06-18T15:10:00Z',
  },
]
