/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    trash: Trash;
    order_counters: OrderCounter;
    users: User;
    media: Media;
    'blog-media': BlogMedia;
    documents: Document;
    addresses: Address;
    categories: Category;
    products: Product;
    carts: Cart;
    wishlists: Wishlist;
    coupons: Coupon;
    orders: Order;
    reviews: Review;
    shippingzones: Shippingzone;
    'blog-posts': BlogPost;
    pages: Page;
    'contact-messages': ContactMessage;
    'email-logs': EmailLog;
    'affiliate-applications': AffiliateApplication;
    affiliates: Affiliate;
    'affiliate-clicks': AffiliateClick;
    'affiliate-conversions': AffiliateConversion;
    'affiliate-payouts': AffiliatePayout;
    'payout-requests': PayoutRequest;
    'processing-fees': ProcessingFee;
    'military-discount-requests': MilitaryDiscountRequest;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    trash: TrashSelect<false> | TrashSelect<true>;
    order_counters: OrderCountersSelect<false> | OrderCountersSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'blog-media': BlogMediaSelect<false> | BlogMediaSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    addresses: AddressesSelect<false> | AddressesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    carts: CartsSelect<false> | CartsSelect<true>;
    wishlists: WishlistsSelect<false> | WishlistsSelect<true>;
    coupons: CouponsSelect<false> | CouponsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    shippingzones: ShippingzonesSelect<false> | ShippingzonesSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'contact-messages': ContactMessagesSelect<false> | ContactMessagesSelect<true>;
    'email-logs': EmailLogsSelect<false> | EmailLogsSelect<true>;
    'affiliate-applications': AffiliateApplicationsSelect<false> | AffiliateApplicationsSelect<true>;
    affiliates: AffiliatesSelect<false> | AffiliatesSelect<true>;
    'affiliate-clicks': AffiliateClicksSelect<false> | AffiliateClicksSelect<true>;
    'affiliate-conversions': AffiliateConversionsSelect<false> | AffiliateConversionsSelect<true>;
    'affiliate-payouts': AffiliatePayoutsSelect<false> | AffiliatePayoutsSelect<true>;
    'payout-requests': PayoutRequestsSelect<false> | PayoutRequestsSelect<true>;
    'processing-fees': ProcessingFeesSelect<false> | ProcessingFeesSelect<true>;
    'military-discount-requests': MilitaryDiscountRequestsSelect<false> | MilitaryDiscountRequestsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'es') | ('en' | 'es')[];
  globals: {
    'affiliate-settings': AffiliateSetting;
    'blog-author-profile': BlogAuthorProfile;
  };
  globalsSelect: {
    'affiliate-settings': AffiliateSettingsSelect<false> | AffiliateSettingsSelect<true>;
    'blog-author-profile': BlogAuthorProfileSelect<false> | BlogAuthorProfileSelect<true>;
  };
  locale: 'en' | 'es';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Deleted documents are stored here. You can restore them or delete them permanently.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trash".
 */
export interface Trash {
  id: number;
  title?: string | null;
  collectionSlug: string;
  originalId: string;
  documentData:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order_counters".
 */
export interface OrderCounter {
  id: number;
  counter: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName?: string | null;
  lastName?: string | null;
  googleId?: string | null;
  authProvider?: ('credentials' | 'google') | null;
  pendingEmail?: string | null;
  pendingEmailCodeHash?: string | null;
  pendingEmailCodeExpiresAt?: string | null;
  phone?: string | null;
  role?: ('customer' | 'admin' | 'staff') | null;
  emailVerified?: boolean | null;
  acceptsMarketing?: boolean | null;
  /**
   * Send SMS notifications for order status updates.
   */
  orderSmsUpdates?: boolean | null;
  preferredLocale?: ('en' | 'es') | null;
  dateOfBirth?: string | null;
  stripeCustomerId?: string | null;
  defaultShippingAddress?: (number | null) | Address;
  defaultBillingAddress?: (number | null) | Address;
  lastLoginAt?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * HB Points ($1 per point). Can be used by users at checkout.
   */
  hbPoints?: number | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses".
 */
export interface Address {
  id: number;
  user: number | User;
  label: string;
  firstName: string;
  lastName: string;
  company?: string | null;
  line1: string;
  line2?: string | null;
  city: string;
  state: string;
  postalCode: string;
  country: string;
  phone: string;
  isDefaultShipping?: boolean | null;
  isDefaultBilling?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-media".
 */
export interface BlogMedia {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  title: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  description?: string | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  slug?: string | null;
  parent?: (number | null) | Category;
  isVisible?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  description?: string | null;
  /**
   * Upload images for the product. The first image is the primary thumbnail.
   */
  images?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  slug?: string | null;
  sku?: string | null;
  price: number;
  /**
   * If set, this price will override the regular price.
   */
  salePrice?: number | null;
  stock: number;
  /**
   * Weight in kg or lbs (depending on global settings)
   */
  weight?: number | null;
  /**
   * Dimensions in cm or inches (depending on global settings)
   */
  dimensions?: {
    length?: number | null;
    width?: number | null;
    height?: number | null;
  };
  categories?: (number | Category)[] | null;
  hasVariants?: boolean | null;
  variants?:
    | {
        sku: string;
        /**
         * Check this if this variant is a multi-item kit (used for coupon filtering).
         */
        isKit?: boolean | null;
        /**
         * Optional specific images for this variant (e.g., 5mg vial vs 10mg kit)
         */
        images?:
          | {
              image: number | Media;
              id?: string | null;
            }[]
          | null;
        price: number;
        salePrice?: number | null;
        stock: number;
        options?:
          | {
              key?: string | null;
              value?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Offer multi-kit bulk bundles of THIS product (e.g., 5 Kits, 10 Kits) directly on the product page.
   */
  bulkBundles?:
    | {
        /**
         * e.g. 5 Kits
         */
        name: string;
        /**
         * Number of items in this bundle
         */
        quantity: number;
        /**
         * Percentage discount off the total (e.g. 15 for 15% off). If set, the bundle dynamically multiplies the selected variant price!
         */
        discountPercentage?: number | null;
        /**
         * Legacy hardcoded price (leave empty if using dynamic discount or overrides)
         */
        price?: number | null;
        /**
         * Legacy hardcoded sale price
         */
        salePrice?: number | null;
        /**
         * Optional image for this specific bundle.
         */
        image?: (number | null) | Media;
        /**
         * Optional: Manually hardcode an exact dollar amount for a specific variant. This bypasses the percentage discount.
         */
        variantOverrides?:
          | {
              /**
               * Select the variant this applies to.
               */
              variantSku: string;
              price: number;
              salePrice?: number | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  averageRating?: number | null;
  reviewCount?: number | null;
  productDetailsTitle?: string | null;
  productDetailsDescription?: string | null;
  researchFocusTitle?: string | null;
  researchFocusDescription?: string | null;
  qualityPurityTitle?: string | null;
  qualityPurityDescription?: string | null;
  complianceNoticeTitle?: string | null;
  complianceNoticeDescription?: string | null;
  /**
   * Upload the Certificate of Analysis (COA) document (PDF/Image)
   */
  coaFile?: (number | null) | Document;
  /**
   * Batch number shown on the /certificates COA library page (e.g. BPC-2603-A)
   */
  coaBatchNumber?: string | null;
  /**
   * Purity/potency percentage shown on the /certificates COA library page (e.g. 99.8). Potency assays can exceed 100% (overfill), so no upper bound is enforced.
   */
  coaPurity?: number | null;
  /**
   * Date the batch was analyzed, shown on the /certificates COA library page
   */
  coaAnalyzedDate?: string | null;
  /**
   * Add frequently asked questions specifically for this product.
   */
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  status?: ('draft' | 'active' | 'archived') | null;
  isVisible?: boolean | null;
  /**
   * Feature this product in the homepage Best Sellers section.
   */
  isBestSeller?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts".
 */
export interface Cart {
  id: number;
  user: number | User;
  items?:
    | {
        product?: (number | null) | Product;
        variantSku: string;
        variantTitle?: string | null;
        quantity: number;
        addedAt: string;
        priceSnapshot: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Records when the abandoned cart email was sent to prevent spamming.
   */
  abandonedEmailSentAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wishlists".
 */
export interface Wishlist {
  id: number;
  userName?: string | null;
  user: number | User;
  items?:
    | {
        product?: (number | null) | Product;
        variantSku: string;
        quantity: number;
        addedAt: string;
        priceSnapshot: number;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons".
 */
export interface Coupon {
  id: number;
  code: string;
  usageCount?: number | null;
  /**
   * Turn off to instantly pause this coupon without deleting its usage history.
   */
  isActive?: boolean | null;
  freeShipping?: boolean | null;
  type: 'percentage' | 'fixed_amount' | 'free_shipping' | 'buy_one_get_one' | 'store_credit';
  /**
   * Minimum order amount (in dollars) required to apply this coupon.
   */
  minSpend?: number | null;
  /**
   * Maximum number of times this coupon can be used globally.
   */
  usageLimit?: number | null;
  /**
   * Allow this coupon to be combined with other coupons on the same order.
   */
  stackable?: boolean | null;
  /**
   * Expiration date after which the coupon is no longer valid.
   */
  expiresAt?: string | null;
  /**
   * If enabled, the coupon will not apply to items on sale.
   */
  excludeSaleItems?: boolean | null;
  /**
   * When true, the coupon is automatically applied at checkout if conditions are met.
   */
  autoApply?: boolean | null;
  /**
   * Only valid for logged-in accounts with no prior orders.
   */
  newCustomersOnly?: boolean | null;
  /**
   * Restrict coupon usage to specific email addresses (leave empty for unrestricted).
   */
  lockedEmails?:
    | {
        email: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Total store credit value in dollars.
   */
  storeCreditAmount?: number | null;
  /**
   * Remaining credit balance. Managed by the system.
   */
  remainingBalance?: number | null;
  /**
   * Percentage (0-100), fixed amount in dollars, or ignored for free shipping.
   */
  value?: number | null;
  /**
   * Restrict coupon usage to single items or kits. Make sure your kit variants have "isKit" checked.
   */
  applicableProductTypes: 'all' | 'normal_only' | 'bulk_only';
  appliesTo: 'all' | 'specific_products' | 'specific_categories';
  products?:
    | {
        product: number | Product;
        id?: string | null;
      }[]
    | null;
  categories?:
    | {
        category: number | Category;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Customer orders – generated server‑side only.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  /**
   * Auto‑generated order identifier (e.g., 7000).
   */
  orderNumber?: string | null;
  /**
   * User who placed the order (null for guests).
   */
  owner?: (number | null) | User;
  /**
   * First name of the customer (useful for guest orders).
   */
  customerFirstName?: string | null;
  customerLastName?: string | null;
  customerPhone?: string | null;
  items?:
    | {
        product?: (number | null) | Product;
        /**
         * The display title of the variant, e.g. "10mg Single" or "10mg 10 Kit (Best Value)"
         */
        variantTitle?: string | null;
        /**
         * The variant SKU or bundle code purchased
         */
        variant?: string | null;
        /**
         * Price paid per unit at the time of order
         */
        price?: number | null;
        quantity: number;
        /**
         * Snapshot of product data at order time. Collapsed to save space.
         */
        productSnapshot?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  shippingAddress?: {
    line1?: string | null;
    line2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
  };
  billingAddress?: {
    line1?: string | null;
    line2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
  };
  status: 'pending' | 'paid' | 'fulfilled' | 'shipped' | 'completed' | 'refunded' | 'cancelled';
  paymentStatus: 'unpaid' | 'authorized' | 'captured' | 'refunded';
  fulfillmentStatus: 'unfulfilled' | 'partial' | 'fulfilled';
  refunds?:
    | {
        amount?: number | null;
        reason?: string | null;
        createdAt?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Before discounts/shipping/tax
   */
  subtotal?: number | null;
  discountTotal?: number | null;
  /**
   * HB Points used in this order ($1 per point)
   */
  redeemedPoints?: number | null;
  shippingTotal?: number | null;
  taxTotal: number;
  /**
   * Total of all applied processing fees in dollars
   */
  feeTotal: number;
  total: number;
  /**
   * Processing fees applied to this order
   */
  appliedFees?:
    | {
        feeId?: (number | null) | ProcessingFee;
        feeName?: string | null;
        /**
         * Amount charged in dollars
         */
        amount?: number | null;
        /**
         * Snapshot of the fee type at the time the order was placed
         */
        feeType?: ('percentage' | 'fixed_amount') | null;
        /**
         * Snapshot of the percentage rate charged at order time (only set when feeType is percentage). This must never be recalculated from the live processing-fees config, so historical orders keep showing the rate actually charged even after the config changes.
         */
        percentage?: number | null;
        id?: string | null;
      }[]
    | null;
  shippingMethod?: string | null;
  /**
   * URL to track the package
   */
  trackingLink?: string | null;
  /**
   * Check this box before saving to email the tracking link to the customer.
   */
  sendTrackingEmail?: boolean | null;
  /**
   * Zelle orders require manual payment confirmation before fulfillment.
   */
  paymentMethod?: ('stripe' | 'zelle' | 'amex' | 'circoflows' | 'stripe_link') | null;
  /**
   * CircoFlows transaction_id, for support/reconciliation lookups.
   */
  circoflowsTransactionId?: string | null;
  couponCode?: string | null;
  /**
   * Affiliate ID if referred
   */
  affiliateId?: string | null;
  /**
   * Affiliate click ID if referred
   */
  clickId?: string | null;
  /**
   * Where this order originated from (e.g. a sibling storefront that redirects its cart here), if not placed directly on this site.
   */
  orderSource?: string | null;
  customerNote?: string | null;
  /**
   * For orders without a registered user account
   */
  guestEmail?: string | null;
  createdAt: string;
  updatedAt: string;
  /**
   * True if inventory, coupons, and points have been processed for this order.
   */
  isFinalized?: boolean | null;
  /**
   * Keep a running history of internal notes or send messages directly to the customer.
   */
  notes?:
    | {
        type: 'internal' | 'customer';
        note: string;
        /**
         * Auto-stamped when you save.
         */
        date?: string | null;
        isEmailed?: boolean | null;
        id?: string | null;
      }[]
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "processing-fees".
 */
export interface ProcessingFee {
  id: number;
  /**
   * The name of the fee displayed to customers (e.g., "Rush Processing", "Insurance")
   */
  name: string;
  /**
   * Amount in dollars (e.g., 2.50) OR percentage (e.g., 3 = 3%) depending on type
   */
  amount: number;
  type: 'fixed_amount' | 'percentage';
  /**
   * If disabled, this fee will not be applied or shown.
   */
  isActive?: boolean | null;
  /**
   * If true, customers must actively check a box to apply this fee. If false, it is mandatory for all orders.
   */
  isOptional?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Customer reviews – verification ties to delivered orders.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  product: number | Product;
  user: number | User;
  order?: (number | null) | Order;
  rating: number;
  comment?: string | null;
  /**
   * Auto‑set to true when linked order is delivered
   */
  verifiedPurchase?: boolean | null;
  status?: ('pending' | 'approved' | 'rejected') | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * Geographic shipping zones with sample shipping methods.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shippingzones".
 */
export interface Shippingzone {
  id: number;
  name: string;
  /**
   * Sample shipping methods for this zone.
   */
  methods?:
    | {
        method: string;
        /**
         * Set to 0 for free shipping
         */
        price: number;
        estimatedDays?: number | null;
        /**
         * Minimum subtotal required for this method to appear (e.g., 100 for free shipping over $100)
         */
        minOrderAmount?: number | null;
        /**
         * Check this for the method that should be used for any order shipping to a country other than the US. It replaces all other methods at checkout and ignores minOrderAmount/free-shipping rules. Only one method should have this checked.
         */
        isInternational?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  slug?: string | null;
  author: number | User;
  featuredImage?: (number | null) | BlogMedia;
  /**
   * Short summary shown on blog listing cards and used as the default SEO/social description.
   */
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  publishedAt?: string | null;
  status?: ('draft' | 'published') | null;
  category?: ('Metabolic research' | 'Recovery protocols' | 'Growth research' | 'Muscle studies') | null;
  relatedProducts?: (number | Product)[] | null;
  /**
   * e.g. '12 min read'. Leave blank to auto-calculate from content length when rendered.
   */
  readTime?: string | null;
  /**
   * Short factual bullet points summarizing the post. Used for AI answer-engine (AEO/GEO) extraction and on-page "Key Takeaways" callouts.
   */
  keyTakeaways?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Populates FAQPage schema.org markup and on-page FAQ accordion.
   */
  faqs?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Peer-reviewed sources cited in this post (PubMed, DOI, journal links). Strengthens E-E-A-T trust signals and AI answer-engine citation likelihood.
   */
  references?:
    | {
        /**
         * e.g. "Smith et al., 2023, Journal of Peptide Science"
         */
        citationText: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Primary target keyword/phrase for this post (editorial SEO guidance).
   */
  focusKeyphrase?: string | null;
  /**
   * Comma-separated secondary keywords for meta keywords / internal search relevance.
   */
  keywords?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  status?: ('draft' | 'published') | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages".
 */
export interface ContactMessage {
  id: number;
  name: string;
  email: string;
  subject?: string | null;
  message: string;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-logs".
 */
export interface EmailLog {
  id: number;
  to: string;
  subject: string;
  body:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  sentAt: string;
  status?: ('sent' | 'failed') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "affiliate-applications".
 */
export interface AffiliateApplication {
  id: number;
  user: number | User;
  status?: ('pending' | 'approved' | 'rejected') | null;
  displayName: string;
  websiteUrl?: string | null;
  socialLinks?:
    | {
        platform?: ('instagram' | 'youtube' | 'tiktok' | 'twitter' | 'reddit') | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  promotionMethods: string;
  estimatedMonthlyReach?: ('<1k' | '1k-10k' | '10k-100k' | '100k+') | null;
  niche?: string | null;
  whyJoin?: string | null;
  agreedToTerms: boolean;
  reviewedBy?: (number | null) | User;
  reviewedAt?: string | null;
  reviewNotes?: string | null;
  linkedAffiliate?: (number | null) | Affiliate;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "affiliates".
 */
export interface Affiliate {
  id: number;
  user: number | User;
  status?: ('pending' | 'approved' | 'rejected' | 'suspended') | null;
  applicationDate?: string | null;
  approvedAt?: string | null;
  approvedBy?: (number | null) | User;
  suspendedAt?: string | null;
  suspensionReason?: string | null;
  displayName?: string | null;
  websiteUrl?: string | null;
  socialLinks?:
    | {
        platform?: ('instagram' | 'youtube' | 'tiktok' | 'twitter' | 'reddit') | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * For Multi-Tier / MLM. The affiliate who recruited this affiliate.
   */
  parentAffiliate?: (number | null) | Affiliate;
  referralSlug?: string | null;
  couponCode?: string | null;
  coupon?: (number | null) | Coupon;
  cookieDurationDays?: number | null;
  /**
   * Leave blank to use Global Default. Percentage of eligible order value or fixed amount in dollars.
   */
  commissionRate?: number | null;
  /**
   * Leave blank to use Global Default.
   */
  commissionType?: ('percentage' | 'fixed_amount') | null;
  /**
   * % discount the customer gets using their coupon
   */
  customerDiscount?: number | null;
  /**
   * Leave blank to use Global Default. Days before commission is approved.
   */
  pendingPeriodDays?: number | null;
  /**
   * Leave blank to use Global Default.
   */
  commissionOn?: ('subtotal_after_coupon' | 'subtotal_before_coupon') | null;
  tier?: ('standard' | 'silver' | 'gold' | 'vip') | null;
  totalClicks?: number | null;
  uniqueClicks?: number | null;
  totalConversions?: number | null;
  /**
   * In dollars
   */
  totalRevenue?: number | null;
  /**
   * In dollars
   */
  totalCommissionEarned?: number | null;
  /**
   * In dollars
   */
  totalCommissionPending?: number | null;
  /**
   * In dollars
   */
  totalCommissionApproved?: number | null;
  /**
   * In dollars (pending/approved payout requests)
   */
  totalCommissionRequested?: number | null;
  /**
   * In dollars
   */
  totalCommissionPaid?: number | null;
  /**
   * Leave blank to use Global Default. Minimum payout threshold in dollars (e.g. 50.00).
   */
  minimumPayoutThreshold?: number | null;
  payoutCurrency?: ('USD' | 'BTC' | 'ETH' | 'USDT_ERC20' | 'USDT_TRC20' | 'STORE_CREDIT') | null;
  payoutMethods?:
    | {
        type?:
          | (
              | 'paypal'
              | 'wise'
              | 'bank_wire'
              | 'crypto_btc'
              | 'crypto_eth'
              | 'crypto_usdt_erc20'
              | 'crypto_usdt_trc20'
              | 'store_credit'
            )
          | null;
        isPrimary?: boolean | null;
        paypalEmail?: string | null;
        walletAddress?: string | null;
        walletNetwork?: string | null;
        id?: string | null;
      }[]
    | null;
  flaggedForReview?: boolean | null;
  fraudScore?: number | null;
  fraudNotes?: string | null;
  adminNotes?: string | null;
  agreedToTermsAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "affiliate-clicks".
 */
export interface AffiliateClick {
  id: number;
  affiliate: number | Affiliate;
  source?: ('referral_link' | 'coupon_code_attempt') | null;
  ipHash?: string | null;
  ipCountry?: string | null;
  userAgent?: string | null;
  deviceType?: ('desktop' | 'mobile' | 'tablet') | null;
  referrer?: string | null;
  landingPage?: string | null;
  sessionId?: string | null;
  convertedToOrder?: boolean | null;
  conversion?: (number | null) | AffiliateConversion;
  /**
   * In dollars
   */
  conversionValue?: number | null;
  isSuspicious?: boolean | null;
  suspicionReason?: string | null;
  clickedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "affiliate-conversions".
 */
export interface AffiliateConversion {
  id: number;
  affiliate: number | Affiliate;
  order: number | Order;
  customer?: (number | null) | User;
  customerEmail?: string | null;
  attributionSource?: ('referral_link' | 'coupon_code' | 'both') | null;
  attributionClick?: (number | null) | AffiliateClick;
  cookieAgeDays?: number | null;
  couponCodeUsed?: string | null;
  orderSubtotal?: number | null;
  orderDiscount?: number | null;
  eligibleSubtotal?: number | null;
  commissionRate?: number | null;
  /**
   * In dollars
   */
  commissionAmount?: number | null;
  status?: ('pending' | 'approved' | 'paid' | 'reversed' | 'voided') | null;
  pendingUntil?: string | null;
  approvedAt?: string | null;
  payout?: (number | null) | AffiliatePayout;
  paidAt?: string | null;
  reversedAt?: string | null;
  reversedReason?: ('order_refunded' | 'order_cancelled' | 'fraud_detected' | 'self_referral' | 'admin_manual') | null;
  reversedBy?: (number | null) | User;
  selfReferralDetected?: boolean | null;
  ipMatchesAffiliate?: boolean | null;
  fraudScore?: number | null;
  flaggedForReview?: boolean | null;
  fraudNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "affiliate-payouts".
 */
export interface AffiliatePayout {
  id: number;
  affiliate: number | Affiliate;
  conversions: (number | AffiliateConversion)[];
  conversionCount?: number | null;
  totalAmountCents: number;
  currency?: ('USD' | 'BTC' | 'ETH' | 'USDT') | null;
  cryptoAmountRaw?: string | null;
  exchangeRateUsed?: number | null;
  paymentMethod?:
    | (
        | 'paypal'
        | 'wise'
        | 'bank_wire'
        | 'crypto_btc'
        | 'crypto_eth'
        | 'crypto_usdt_erc20'
        | 'crypto_usdt_trc20'
        | 'store_credit'
      )
    | null;
  paymentDestination?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status?: ('draft' | 'processing' | 'paid' | 'failed') | null;
  createdBy?: (number | null) | User;
  processedBy?: (number | null) | User;
  adminNotes?: string | null;
  transactionId?: string | null;
  receiptFile?: (number | null) | Media;
  receiptUrl?: string | null;
  exportedAt?: string | null;
  paidAt?: string | null;
  failedAt?: string | null;
  failureReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payout-requests".
 */
export interface PayoutRequest {
  id: number;
  affiliate: number | Affiliate;
  /**
   * Amount requested in dollars
   */
  amount: number;
  payoutMethod: 'zelle' | 'cashapp' | 'applepay';
  /**
   * Phone number, CashTag, or ApplePay ID
   */
  payoutDetails: string;
  status: 'pending' | 'approved' | 'paid' | 'rejected';
  processedAt?: string | null;
  processedBy?: (number | null) | User;
  adminNotes?: string | null;
  rejectionReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * ID photos are never stored here — they are emailed to support for manual review and are not retained.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "military-discount-requests".
 */
export interface MilitaryDiscountRequest {
  id: number;
  fullName: string;
  email: string;
  branch: string;
  status: 'pending' | 'approved' | 'rejected';
  /**
   * The one-time, email-locked coupon generated when this request was approved.
   */
  couponCode?: string | null;
  reviewedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'trash';
        value: number | Trash;
      } | null)
    | ({
        relationTo: 'order_counters';
        value: number | OrderCounter;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'blog-media';
        value: number | BlogMedia;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'addresses';
        value: number | Address;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'carts';
        value: number | Cart;
      } | null)
    | ({
        relationTo: 'wishlists';
        value: number | Wishlist;
      } | null)
    | ({
        relationTo: 'coupons';
        value: number | Coupon;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'shippingzones';
        value: number | Shippingzone;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'contact-messages';
        value: number | ContactMessage;
      } | null)
    | ({
        relationTo: 'email-logs';
        value: number | EmailLog;
      } | null)
    | ({
        relationTo: 'affiliate-applications';
        value: number | AffiliateApplication;
      } | null)
    | ({
        relationTo: 'affiliates';
        value: number | Affiliate;
      } | null)
    | ({
        relationTo: 'affiliate-clicks';
        value: number | AffiliateClick;
      } | null)
    | ({
        relationTo: 'affiliate-conversions';
        value: number | AffiliateConversion;
      } | null)
    | ({
        relationTo: 'affiliate-payouts';
        value: number | AffiliatePayout;
      } | null)
    | ({
        relationTo: 'payout-requests';
        value: number | PayoutRequest;
      } | null)
    | ({
        relationTo: 'processing-fees';
        value: number | ProcessingFee;
      } | null)
    | ({
        relationTo: 'military-discount-requests';
        value: number | MilitaryDiscountRequest;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trash_select".
 */
export interface TrashSelect<T extends boolean = true> {
  title?: T;
  collectionSlug?: T;
  originalId?: T;
  documentData?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order_counters_select".
 */
export interface OrderCountersSelect<T extends boolean = true> {
  id?: T;
  counter?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  googleId?: T;
  authProvider?: T;
  pendingEmail?: T;
  pendingEmailCodeHash?: T;
  pendingEmailCodeExpiresAt?: T;
  phone?: T;
  role?: T;
  emailVerified?: T;
  acceptsMarketing?: T;
  orderSmsUpdates?: T;
  preferredLocale?: T;
  dateOfBirth?: T;
  stripeCustomerId?: T;
  defaultShippingAddress?: T;
  defaultBillingAddress?: T;
  lastLoginAt?: T;
  metadata?: T;
  hbPoints?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-media_select".
 */
export interface BlogMediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses_select".
 */
export interface AddressesSelect<T extends boolean = true> {
  user?: T;
  label?: T;
  firstName?: T;
  lastName?: T;
  company?: T;
  line1?: T;
  line2?: T;
  city?: T;
  state?: T;
  postalCode?: T;
  country?: T;
  phone?: T;
  isDefaultShipping?: T;
  isDefaultBilling?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  seoTitle?: T;
  seoDescription?: T;
  slug?: T;
  parent?: T;
  isVisible?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  seoTitle?: T;
  seoDescription?: T;
  slug?: T;
  sku?: T;
  price?: T;
  salePrice?: T;
  stock?: T;
  weight?: T;
  dimensions?:
    | T
    | {
        length?: T;
        width?: T;
        height?: T;
      };
  categories?: T;
  hasVariants?: T;
  variants?:
    | T
    | {
        sku?: T;
        isKit?: T;
        images?:
          | T
          | {
              image?: T;
              id?: T;
            };
        price?: T;
        salePrice?: T;
        stock?: T;
        options?:
          | T
          | {
              key?: T;
              value?: T;
              id?: T;
            };
        id?: T;
      };
  bulkBundles?:
    | T
    | {
        name?: T;
        quantity?: T;
        discountPercentage?: T;
        price?: T;
        salePrice?: T;
        image?: T;
        variantOverrides?:
          | T
          | {
              variantSku?: T;
              price?: T;
              salePrice?: T;
              id?: T;
            };
        id?: T;
      };
  averageRating?: T;
  reviewCount?: T;
  productDetailsTitle?: T;
  productDetailsDescription?: T;
  researchFocusTitle?: T;
  researchFocusDescription?: T;
  qualityPurityTitle?: T;
  qualityPurityDescription?: T;
  complianceNoticeTitle?: T;
  complianceNoticeDescription?: T;
  coaFile?: T;
  coaBatchNumber?: T;
  coaPurity?: T;
  coaAnalyzedDate?: T;
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  status?: T;
  isVisible?: T;
  isBestSeller?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts_select".
 */
export interface CartsSelect<T extends boolean = true> {
  user?: T;
  items?:
    | T
    | {
        product?: T;
        variantSku?: T;
        variantTitle?: T;
        quantity?: T;
        addedAt?: T;
        priceSnapshot?: T;
        id?: T;
      };
  abandonedEmailSentAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wishlists_select".
 */
export interface WishlistsSelect<T extends boolean = true> {
  userName?: T;
  user?: T;
  items?:
    | T
    | {
        product?: T;
        variantSku?: T;
        quantity?: T;
        addedAt?: T;
        priceSnapshot?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coupons_select".
 */
export interface CouponsSelect<T extends boolean = true> {
  code?: T;
  usageCount?: T;
  isActive?: T;
  freeShipping?: T;
  type?: T;
  minSpend?: T;
  usageLimit?: T;
  stackable?: T;
  expiresAt?: T;
  excludeSaleItems?: T;
  autoApply?: T;
  newCustomersOnly?: T;
  lockedEmails?:
    | T
    | {
        email?: T;
        id?: T;
      };
  storeCreditAmount?: T;
  remainingBalance?: T;
  value?: T;
  applicableProductTypes?: T;
  appliesTo?: T;
  products?:
    | T
    | {
        product?: T;
        id?: T;
      };
  categories?:
    | T
    | {
        category?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  owner?: T;
  customerFirstName?: T;
  customerLastName?: T;
  customerPhone?: T;
  items?:
    | T
    | {
        product?: T;
        variantTitle?: T;
        variant?: T;
        price?: T;
        quantity?: T;
        productSnapshot?: T;
        id?: T;
      };
  shippingAddress?:
    | T
    | {
        line1?: T;
        line2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
      };
  billingAddress?:
    | T
    | {
        line1?: T;
        line2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
      };
  status?: T;
  paymentStatus?: T;
  fulfillmentStatus?: T;
  refunds?:
    | T
    | {
        amount?: T;
        reason?: T;
        createdAt?: T;
        id?: T;
      };
  subtotal?: T;
  discountTotal?: T;
  redeemedPoints?: T;
  shippingTotal?: T;
  taxTotal?: T;
  feeTotal?: T;
  total?: T;
  appliedFees?:
    | T
    | {
        feeId?: T;
        feeName?: T;
        amount?: T;
        feeType?: T;
        percentage?: T;
        id?: T;
      };
  shippingMethod?: T;
  trackingLink?: T;
  sendTrackingEmail?: T;
  paymentMethod?: T;
  circoflowsTransactionId?: T;
  couponCode?: T;
  affiliateId?: T;
  clickId?: T;
  orderSource?: T;
  customerNote?: T;
  guestEmail?: T;
  createdAt?: T;
  updatedAt?: T;
  isFinalized?: T;
  notes?:
    | T
    | {
        type?: T;
        note?: T;
        date?: T;
        isEmailed?: T;
        id?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  product?: T;
  user?: T;
  order?: T;
  rating?: T;
  comment?: T;
  verifiedPurchase?: T;
  status?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shippingzones_select".
 */
export interface ShippingzonesSelect<T extends boolean = true> {
  name?: T;
  methods?:
    | T
    | {
        method?: T;
        price?: T;
        estimatedDays?: T;
        minOrderAmount?: T;
        isInternational?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  author?: T;
  featuredImage?: T;
  excerpt?: T;
  content?: T;
  publishedAt?: T;
  status?: T;
  category?: T;
  relatedProducts?: T;
  readTime?: T;
  keyTakeaways?:
    | T
    | {
        text?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  references?:
    | T
    | {
        citationText?: T;
        url?: T;
        id?: T;
      };
  focusKeyphrase?: T;
  keywords?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  status?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages_select".
 */
export interface ContactMessagesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  subject?: T;
  message?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-logs_select".
 */
export interface EmailLogsSelect<T extends boolean = true> {
  to?: T;
  subject?: T;
  body?: T;
  sentAt?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "affiliate-applications_select".
 */
export interface AffiliateApplicationsSelect<T extends boolean = true> {
  user?: T;
  status?: T;
  displayName?: T;
  websiteUrl?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  promotionMethods?: T;
  estimatedMonthlyReach?: T;
  niche?: T;
  whyJoin?: T;
  agreedToTerms?: T;
  reviewedBy?: T;
  reviewedAt?: T;
  reviewNotes?: T;
  linkedAffiliate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "affiliates_select".
 */
export interface AffiliatesSelect<T extends boolean = true> {
  user?: T;
  status?: T;
  applicationDate?: T;
  approvedAt?: T;
  approvedBy?: T;
  suspendedAt?: T;
  suspensionReason?: T;
  displayName?: T;
  websiteUrl?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  parentAffiliate?: T;
  referralSlug?: T;
  couponCode?: T;
  coupon?: T;
  cookieDurationDays?: T;
  commissionRate?: T;
  commissionType?: T;
  customerDiscount?: T;
  pendingPeriodDays?: T;
  commissionOn?: T;
  tier?: T;
  totalClicks?: T;
  uniqueClicks?: T;
  totalConversions?: T;
  totalRevenue?: T;
  totalCommissionEarned?: T;
  totalCommissionPending?: T;
  totalCommissionApproved?: T;
  totalCommissionRequested?: T;
  totalCommissionPaid?: T;
  minimumPayoutThreshold?: T;
  payoutCurrency?: T;
  payoutMethods?:
    | T
    | {
        type?: T;
        isPrimary?: T;
        paypalEmail?: T;
        walletAddress?: T;
        walletNetwork?: T;
        id?: T;
      };
  flaggedForReview?: T;
  fraudScore?: T;
  fraudNotes?: T;
  adminNotes?: T;
  agreedToTermsAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "affiliate-clicks_select".
 */
export interface AffiliateClicksSelect<T extends boolean = true> {
  affiliate?: T;
  source?: T;
  ipHash?: T;
  ipCountry?: T;
  userAgent?: T;
  deviceType?: T;
  referrer?: T;
  landingPage?: T;
  sessionId?: T;
  convertedToOrder?: T;
  conversion?: T;
  conversionValue?: T;
  isSuspicious?: T;
  suspicionReason?: T;
  clickedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "affiliate-conversions_select".
 */
export interface AffiliateConversionsSelect<T extends boolean = true> {
  affiliate?: T;
  order?: T;
  customer?: T;
  customerEmail?: T;
  attributionSource?: T;
  attributionClick?: T;
  cookieAgeDays?: T;
  couponCodeUsed?: T;
  orderSubtotal?: T;
  orderDiscount?: T;
  eligibleSubtotal?: T;
  commissionRate?: T;
  commissionAmount?: T;
  status?: T;
  pendingUntil?: T;
  approvedAt?: T;
  payout?: T;
  paidAt?: T;
  reversedAt?: T;
  reversedReason?: T;
  reversedBy?: T;
  selfReferralDetected?: T;
  ipMatchesAffiliate?: T;
  fraudScore?: T;
  flaggedForReview?: T;
  fraudNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "affiliate-payouts_select".
 */
export interface AffiliatePayoutsSelect<T extends boolean = true> {
  affiliate?: T;
  conversions?: T;
  conversionCount?: T;
  totalAmountCents?: T;
  currency?: T;
  cryptoAmountRaw?: T;
  exchangeRateUsed?: T;
  paymentMethod?: T;
  paymentDestination?: T;
  status?: T;
  createdBy?: T;
  processedBy?: T;
  adminNotes?: T;
  transactionId?: T;
  receiptFile?: T;
  receiptUrl?: T;
  exportedAt?: T;
  paidAt?: T;
  failedAt?: T;
  failureReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payout-requests_select".
 */
export interface PayoutRequestsSelect<T extends boolean = true> {
  affiliate?: T;
  amount?: T;
  payoutMethod?: T;
  payoutDetails?: T;
  status?: T;
  processedAt?: T;
  processedBy?: T;
  adminNotes?: T;
  rejectionReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "processing-fees_select".
 */
export interface ProcessingFeesSelect<T extends boolean = true> {
  name?: T;
  amount?: T;
  type?: T;
  isActive?: T;
  isOptional?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "military-discount-requests_select".
 */
export interface MilitaryDiscountRequestsSelect<T extends boolean = true> {
  fullName?: T;
  email?: T;
  branch?: T;
  status?: T;
  couponCode?: T;
  reviewedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "affiliate-settings".
 */
export interface AffiliateSetting {
  id: number;
  /**
   * Global default commission percentage applied to all affiliates unless individually overridden.
   */
  defaultCommissionRate: number;
  /**
   * Global default commission type.
   */
  defaultCommissionType: 'percentage' | 'fixed_amount';
  /**
   * Global default base for calculating commission.
   */
  defaultCommissionOn: 'subtotal_after_coupon' | 'subtotal_before_coupon';
  defaultCookieDurationDays: number;
  defaultPendingPeriodDays: number;
  /**
   * Global default minimum payout threshold in dollars (e.g. 50.00).
   */
  defaultMinimumPayoutThreshold: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The single byline used across every blog post (the Helix Bio Team account is the only author). Feeds Author/Person schema.org markup for E-E-A-T.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-author-profile".
 */
export interface BlogAuthorProfile {
  id: number;
  name: string;
  /**
   * e.g. "Research & Product Team"
   */
  title?: string | null;
  /**
   * Short author bio shown on post pages and used in Author/Person schema.
   */
  bio?: string | null;
  /**
   * e.g. "Reviewed by in-house research chemists"
   */
  credentials?: string | null;
  photo?: (number | null) | BlogMedia;
  socialLinks?:
    | {
        platform: 'X' | 'LinkedIn' | 'Instagram' | 'Facebook' | 'YouTube';
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "affiliate-settings_select".
 */
export interface AffiliateSettingsSelect<T extends boolean = true> {
  defaultCommissionRate?: T;
  defaultCommissionType?: T;
  defaultCommissionOn?: T;
  defaultCookieDurationDays?: T;
  defaultPendingPeriodDays?: T;
  defaultMinimumPayoutThreshold?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-author-profile_select".
 */
export interface BlogAuthorProfileSelect<T extends boolean = true> {
  name?: T;
  title?: T;
  bio?: T;
  credentials?: T;
  photo?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}